apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgre
spec:
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=60
    - retrans=10
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.0.100
    path: "/shares/sha/var/lib/postgresql/data"
  persistentVolumeReclaimPolicy: "Delete"
  storageClassName: "csi-ceph-hdd-gz1"
