---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgre
  namespace: hw-04
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: "pv-postgre"
  storageClassName: "csi-ceph-hdd-gz1"
