---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redmine
  labels:
    app: redmine-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine-app
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000 
          protocol: TCP
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            value: "testuser" 
          - name: REDMINE_DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: my-secret 
                key: PASS              
          - name: REDMINE_DB_DATABASE
            value: "testdatabase"
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom: 
              secretKeyRef:
                name: supersecretkey
                key: PASS
